USE [master]
GO

/****** Object:  Database [weather app]    Script Date: 1/6/2021 5:57:31 PM ******/
CREATE DATABASE [weather app]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'weather app', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\weather app.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'weather app_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\weather app_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [weather app].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [weather app] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [weather app] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [weather app] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [weather app] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [weather app] SET ARITHABORT OFF 
GO

ALTER DATABASE [weather app] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [weather app] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [weather app] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [weather app] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [weather app] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [weather app] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [weather app] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [weather app] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [weather app] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [weather app] SET  DISABLE_BROKER 
GO

ALTER DATABASE [weather app] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [weather app] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [weather app] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [weather app] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [weather app] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [weather app] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [weather app] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [weather app] SET RECOVERY FULL 
GO

ALTER DATABASE [weather app] SET  MULTI_USER 
GO

ALTER DATABASE [weather app] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [weather app] SET DB_CHAINING OFF 
GO

ALTER DATABASE [weather app] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [weather app] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [weather app] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [weather app] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [weather app] SET QUERY_STORE = OFF
GO

ALTER DATABASE [weather app] SET  READ_WRITE 
GO


